# Generated by Django 6.0.4 on 2026-04-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_campaign_id_alter_claim_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('receipt_no', models.CharField(blank=True, default='', max_length=100)),
                ('user_name', models.CharField(blank=True, default='', max_length=200)),
                ('store_name', models.CharField(blank=True, default='', max_length=200)),
                ('voucher_name', models.CharField(blank=True, default='', max_length=200)),
                ('voucher_code', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Redeemed', 'Redeemed'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Redeemed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
