# Generated by Django 6.0.4 on 2026-05-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_transaction_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='spending_target',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
