# Generated by Django 4.2.29 on 2026-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
