# Generated by Django 4.2.29 on 2026-05-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_campaign_budget_alter_campaign_spending_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
