# Generated by Django 4.2.11 on 2026-05-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_voucher_campaign_protect_txn_id_retry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('Fashion', 'Fashion'), ('Food & Beverage', 'Food & Beverage'), ('Entertainment', 'Entertainment'), ('Beauty', 'Beauty'), ('Electronics', 'Electronics'), ('Sports & Fitness', 'Sports & Fitness'), ('Home & Living', 'Home & Living'), ('Travel', 'Travel'), ('Health & Wellness', 'Health & Wellness')], max_length=50),
        ),
    ]
