# Generated by Django 4.2.11 on 2026-05-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_voucher_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_ref',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
